CREATE TABLE IF NOT EXISTS MASTER_USER (
    ID INT NOT NULL PRIMARY KEY,
    NAME VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS MASTER_TICKET (
    ID INT NOT NULL PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    CAPACITY INT NOT NULL,
    AVAILABILITY INT NOT NULL,
    SALES_BEGIN TIMESTAMP NOT NULL,
    SALES_END TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_TICKET (
    ID INT NOT NULL PRIMARY KEY,
    USER_ID INT NOT NULL,
    TICKET_ID INT NOT NULL,
    AMOUNT INT NOT NULL
);